#include "FormesGeometriques.h"




double FormesGeometriques::CalculerSurface(int double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86-39044a9a:19a7727bccf:-8000:0000000000000C47 begin
{
    return 0.0;
}
// section 10--28--98-86-39044a9a:19a7727bccf:-8000:0000000000000C47 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::CalculerPerimetre(int double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86-39044a9a:19a7727bccf:-8000:0000000000000C4A begin
{
    return 0.0;
}
// section 10--28--98-86-39044a9a:19a7727bccf:-8000:0000000000000C4A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetSurface()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86-39044a9a:19a7727bccf:-8000:0000000000000C4D begin
{
    return 0.0;
}
// section 10--28--98-86-39044a9a:19a7727bccf:-8000:0000000000000C4D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetPerimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86-39044a9a:19a7727bccf:-8000:0000000000000C4F begin
{
    return 0.0;
}
// section 10--28--98-86-39044a9a:19a7727bccf:-8000:0000000000000C4F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
