#include "Rectengle.h"




double Rectengle::CalculerSurface(double Largeur, double Hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86-411b2bc1:19a9208fee9:-8000:0000000000000C3A begin
{
    return 0.0;
}
// section 10--28--98-86-411b2bc1:19a9208fee9:-8000:0000000000000C3A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Rectengle::CalculerPerimetre(double Largeur, double Hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86-411b2bc1:19a9208fee9:-8000:0000000000000C3E begin
{
    return 0.0;
}
// section 10--28--98-86-411b2bc1:19a9208fee9:-8000:0000000000000C3E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
