#include "TriangleRectangle.h"




double TriangleRectangle::CalculerSurface(double Base, double Hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86-411b2bc1:19a9208fee9:-8000:0000000000000C32 begin
{
    return 0.0;
}
// section 10--28--98-86-411b2bc1:19a9208fee9:-8000:0000000000000C32 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double TriangleRectangle::CalculerPerimetre(double Base, double Hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86-411b2bc1:19a9208fee9:-8000:0000000000000C36 begin
{
    return 0.0;
}
// section 10--28--98-86-411b2bc1:19a9208fee9:-8000:0000000000000C36 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
