#include "Cercle.h"




double Cercle::CalculerSurface(double Diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86-411b2bc1:19a9208fee9:-8000:0000000000000C44 begin
{
    return 0.0;
}
// section 10--28--98-86-411b2bc1:19a9208fee9:-8000:0000000000000C44 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Cercle::CalculerPerimetre(double Diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86-411b2bc1:19a9208fee9:-8000:0000000000000C47 begin
{
    return 0.0;
}
// section 10--28--98-86-411b2bc1:19a9208fee9:-8000:0000000000000C47 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
