#include "Ex1.h"




void Ex1::SaisirParametres(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86-39044a9a:19a7727bccf:-8000:0000000000000C13 begin
{
    
}
// section 10--28--98-86-39044a9a:19a7727bccf:-8000:0000000000000C13 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Ex1::main()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86-39044a9a:19a7727bccf:-8000:0000000000000C27 begin
{
    return 0;
}
// section 10--28--98-86-39044a9a:19a7727bccf:-8000:0000000000000C27 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::ExecuterLesCalculs(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86-39044a9a:19a7727bccf:-8000:0000000000000C29 begin
{
    
}
// section 10--28--98-86-39044a9a:19a7727bccf:-8000:0000000000000C29 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::AfficherResultats(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86-39044a9a:19a7727bccf:-8000:0000000000000C2D begin
{
    
}
// section 10--28--98-86-39044a9a:19a7727bccf:-8000:0000000000000C2D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Ex1::ChoisirForme()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86-39044a9a:19a7727bccf:-8000:0000000000000C30 begin
{
    return 0;
}
// section 10--28--98-86-39044a9a:19a7727bccf:-8000:0000000000000C30 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
