#include "Cercle.h"




double Cercle::CalculerSurface(double Diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E6F begin
{
    return 0.0;
}
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E6F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Cercle::CalculerPerimetre(double Diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E72 begin
{
    return 0.0;
}
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E72 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
