#include "Ex1.h"




int Ex1::main()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E2B begin
{
    return 0;
}
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E2B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Ex1::ChoisirForme()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E2D begin
{
    return 0;
}
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E2D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::SaisirParametres(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E2F begin
{
    
}
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E2F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::ExecuterLesCalculs(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E34 begin
{
    
}
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E34 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::AfficherResultats(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E38 begin
{
    
}
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E38 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
