#include "FormesGeometriques.h"




double FormesGeometriques::CalculerSurface(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E3C begin
{
    return 0.0;
}
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E3C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::CalculerPerimetre(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E49 begin
{
    return 0.0;
}
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E49 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetSurface()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E52 begin
{
    return 0.0;
}
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E52 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetPerimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E54 begin
{
    return 0.0;
}
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E54 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
