#include "Rectangle.h"




double Rectangle::CalculerSurface(double Largeur, double Hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E67 begin
{
    return 0.0;
}
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E67 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Rectangle::CalculerPerimetre(double Largeur, double Hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E6B begin
{
    return 0.0;
}
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E6B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
