#include "TriangleRectangle.h"




double TriangleRectangle::CalculerSurface(double Base, double Hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E5E begin
{
    return 0.0;
}
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E5E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double TriangleRectangle::CalculerPerimetre(double Base, double Hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E62 begin
{
    return 0.0;
}
// section 10--28--98-99-5ab32207:19a9af5472b:-8000:0000000000000E62 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
