#include "Dessinateur.h"

Dessinateur::Dessinateur()
{
    m_MaFigure = nullptr;
    m_FigureChoisie = ' ';
}

Dessinateur::~Dessinateur()
{
    SupprimerFigure();
}

void Dessinateur::SupprimerFigure()
{
    if (m_MaFigure != nullptr)
    {
        delete m_MaFigure;
        m_MaFigure = nullptr;
    }
}

void Dessinateur::ConstruireFigure(signed char Choix)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-33-77d6db45:13c586c4ff5:-8000:0000000000000CAD begin
{
    SupprimerFigure();

    m_FigureChoisie = Choix;

    switch (m_FigureChoisie)
    {
    case 'L':
        m_MaFigure = new Ligne();
        break;

    case 'R':
        m_MaFigure = new Rectangle();
        break;

    case 'E':
        m_MaFigure = new Ellipse();
        break;
    }
}
// section -64--88-1-33-77d6db45:13c586c4ff5:-8000:0000000000000CAD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Dessinateur::SaisirPositionXY(int NoPoint)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-33--f43e65:13c5870e6ba:-8000:0000000000000B0C begin
{
    if (m_MaFigure != nullptr)
    {
        m_MaFigure->EffectuerSaisie(NoPoint);
    }
}
// section -64--88-1-33--f43e65:13c5870e6ba:-8000:0000000000000B0C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Dessinateur::DessinerFigure()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-33--f43e65:13c5870e6ba:-8000:0000000000000B0F begin
{
    if (m_MaFigure != nullptr)
    {
        m_MaFigure->Dessiner();
    }
}
// section -64--88-1-33--f43e65:13c5870e6ba:-8000:0000000000000B0F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element