#include "Ellipse.h"




void Ellipse::EffectuerSaisie(int NoPoint)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B4C begin
{
    
}
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B4C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ellipse::Dessiner()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B4F begin
{
    
}
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B4F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Ellipse::Ellipse()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B51 begin
{
}
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B51 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Ellipse::~Ellipse()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B53 begin
{
}
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B53 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
