#include "Ligne.h"




void Ligne::EffectuerSaisie(int NoPoint)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-75afad:13c59679ed7:-8000:0000000000000D8F begin
{
    
}
// section -64--88-1-58-75afad:13c59679ed7:-8000:0000000000000D8F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ligne::Dessiner()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-75afad:13c59679ed7:-8000:0000000000000D92 begin
{
    
}
// section -64--88-1-58-75afad:13c59679ed7:-8000:0000000000000D92 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Ligne::Ligne()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-75afad:13c59679ed7:-8000:0000000000000D94 begin
{
}
// section -64--88-1-58-75afad:13c59679ed7:-8000:0000000000000D94 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Ligne::~Ligne()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-75afad:13c59679ed7:-8000:0000000000000D99 begin
{
}
// section -64--88-1-58-75afad:13c59679ed7:-8000:0000000000000D99 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
