#include "Point.h"




void Point::AfficherPoint()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-33--f43e65:13c5870e6ba:-8000:0000000000000B19 begin
{
    
}
// section -64--88-1-33--f43e65:13c5870e6ba:-8000:0000000000000B19 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Point::SetXY(double ValX, double ValY)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B5D begin
{
    
}
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B5D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Point::GetX()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B61 begin
{
    return 0.0;
}
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B61 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Point::GetY()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B63 begin
{
    return 0.0;
}
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B63 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
