#include "Rectangle.h"




void Rectangle::EffectuerSaisie(int NoPoint)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B43 begin
{
    
}
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B43 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Rectangle::Dessiner()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B46 begin
{
    
}
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B46 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Rectangle::Rectangle()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B48 begin
{
}
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B48 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Rectangle::~Rectangle()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B4A begin
{
}
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B4A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
