#include "Cercle.h"




double Cercle::CalculerSurface(double Diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-124-79797629:1931c95eeec:-8000:0000000000000E67 begin
{
    return 0.0;
}
// section -64--88-1-124-79797629:1931c95eeec:-8000:0000000000000E67 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Cercle::CalculerPerimetre(double Diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-124-79797629:1931c95eeec:-8000:0000000000000E69 begin
{
    return 0.0;
}
// section -64--88-1-124-79797629:1931c95eeec:-8000:0000000000000E69 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
