#include "Ex1.h"




int Ex1::main()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E3C begin
{
    return 0;
}
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E3C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::SaisirParametres(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E45 begin
{
    
}
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E45 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::AfficherResultats(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E48 begin
{
    
}
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E48 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::ExecuterLesCalculs(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E4B begin
{
    
}
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E4B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Ex1::ChoisirForme()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E4E begin
{
    return 0;
}
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E4E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
