#include "FormesGeometriques.h"




void FormesGeometriques::CalculerSurface(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E58 begin
{
}
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E58 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void FormesGeometriques::CalculerPerimetre(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E5B begin
{
    
}
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E5B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetSurface()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E5E begin
{
    return 0.0;
}
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E5E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetPerimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E60 begin
{
    return 0.0;
}
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E60 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
