#include "Rectangle.h"




double Rectangle::CalculerSurface(double Largeur, double Hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-124-79797629:1931c95eeec:-8000:0000000000000E5B begin
{
    return 0.0;
}
// section -64--88-1-124-79797629:1931c95eeec:-8000:0000000000000E5B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Rectangle::CalculerPerimetre(double Largeur, double Hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-124-79797629:1931c95eeec:-8000:0000000000000E5F begin
{
    return 0.0;
}
// section -64--88-1-124-79797629:1931c95eeec:-8000:0000000000000E5F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
