#include "TriangleRectangle.h"




double TriangleRectangle::CalculerSurface(double Base, double Hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E67 begin
{
    return 0.0;
}
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E67 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double TriangleRectangle::CalculePerimetre(double Base, double Hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-124-79797629:1931c95eeec:-8000:0000000000000E57 begin
{
    return 0.0;
}
// section -64--88-1-124-79797629:1931c95eeec:-8000:0000000000000E57 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
