#include "AfficheurLCD.h"




void AfficheurLCD::AfficherCaractere(char c)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-34-12a9f690:13b5252b16c:-8000:0000000000000A14 begin
{
    
}
// section -64--88-1-34-12a9f690:13b5252b16c:-8000:0000000000000A14 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void AfficheurLCD::AfficherText(String Text)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-34-12a9f690:13b5252b16c:-8000:0000000000000A17 begin
{
    
}
// section -64--88-1-34-12a9f690:13b5252b16c:-8000:0000000000000A17 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void AfficheurLCD::Positionner(int Ligne, int Colonne)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-34-12a9f690:13b5252b16c:-8000:0000000000000A1A begin
{
    
}
// section -64--88-1-34-12a9f690:13b5252b16c:-8000:0000000000000A1A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void AfficheurLCD::Initialiser()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-34-12a9f690:13b5252b16c:-8000:0000000000000A1E begin
{
    
}
// section -64--88-1-34-12a9f690:13b5252b16c:-8000:0000000000000A1E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int AfficheurLCD::GetNbDeLignes()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-34-7a30ae0b:13b5b9e93c7:-8000:0000000000000C1A begin
{
    return 0;
}
// section -64--88-1-34-7a30ae0b:13b5b9e93c7:-8000:0000000000000C1A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int AfficheurLCD::GetNbCarParLigne()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-34-7a30ae0b:13b5b9e93c7:-8000:0000000000000C1C begin
{
    return 0;
}
// section -64--88-1-34-7a30ae0b:13b5b9e93c7:-8000:0000000000000C1C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

AfficheurLCD::AfficheurLCD()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86-26eda2ca:19b977f39dd:-8000:0000000000000C25 begin
{
}
// section 10--28--98-86-26eda2ca:19b977f39dd:-8000:0000000000000C25 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

AfficheurLCD::AfficheurLCD(int NbLignes, int NbColonnes)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86-26eda2ca:19b977f39dd:-8000:0000000000000C27 begin
{
}
// section 10--28--98-86-26eda2ca:19b977f39dd:-8000:0000000000000C27 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

AfficheurLCD::~AfficheurLCD()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86-26eda2ca:19b977f39dd:-8000:0000000000000C29 begin
{
}
// section 10--28--98-86-26eda2ca:19b977f39dd:-8000:0000000000000C29 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void AfficheurLCD::ShowDisplay()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86-26eda2ca:19b977f39dd:-8000:0000000000000C2B begin
{
    
}
// section 10--28--98-86-26eda2ca:19b977f39dd:-8000:0000000000000C2B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
